import numpy as np

S_Z_dict={"H":1.0,"C":6.0,"N":7.0,"O":8.0}


def energy_run(S,conf,out_file):
    with open(out_file,"w") as f:
        f.write("! Energy computation Gamess input file\n")
        f.write("! Input autogenerated by python script\n")
        f.write("! \n")

        f.write(" $CONTRL\n")
        f.write("  SCFTYP=RHF\n")
        f.write("  DFTTYP=B3LYPV3\n")
        f.write("  RUNTYP=ENERGY\n")
        # f.write("  COORD=PRINAXIS\n")
        f.write("  NOSYM=1\n")
        f.write("  MPLEVL=0\n")
        f.write("  ICHARG=0\n")
        f.write("  MULT=1\n")
        f.write("  NPRINT=-5\n")
        f.write("  MAXIT=50\n")
        f.write(" $END\n")

        f.write(" $DFT\n")
        # f.write("  JANS=2\n")
        f.write("  NRAD=99\n")
        f.write("  NLEB=590\n")
        f.write(" $END\n")

        f.write(" $SCF\n")
        f.write("  CONV=1.0D-6\n")
        f.write("  MAXVT=50\n")
        f.write(" $END\n")

        f.write(" $SYSTEM\n")
        f.write("  MWORDS=50\n")
        f.write(" $END\n")
        #6-311++G(d,p) basis set
        f.write(" $BASIS\n")
        f.write("  GBASIS=N311\n")
        f.write("  NGAUSS=6\n")
        f.write("  NDFUNC=1\n")
        f.write("  NPFUNC=1\n")
        f.write("  DIFFSP=.TRUE.\n")
        f.write("  DIFFS=.TRUE.\n")
        f.write(" $END\n")
        f.write(" $GUESS\n")
        f.write("  GUESS=HUCKEL\n")
        f.write(" $END\n")

        f.write(" $DATA\n")
        f.write("Comment card\n")
        f.write("C1\n")
        for i in range(conf.shape[1]):
            f.write(f"{S[i]:2s} {S_Z_dict[S[i]]:4.1f}  {conf[0,i]:14.10f} {conf[1,i]:14.10f} {conf[2,i]:14.10f}\n")
        f.write(" $END\n")
    return

def opt_run(S,conf,out_file,atom1=None,atom2=None):
    with open(out_file,"w") as f:
        f.write("! Energy computation Gamess input file\n")
        f.write("! Input autogenerated by python script\n")
        f.write("! \n")

        f.write(" $CONTRL\n")
        f.write("  SCFTYP=RHF\n")
        f.write("  DFTTYP=B3LYPV3\n")
        f.write("  RUNTYP=OPTIMIZE\n")
        # f.write("  COORD=PRINAXIS\n")
        f.write("  NOSYM=1\n")
        f.write("  MPLEVL=0\n")
        f.write("  ICHARG=0\n")
        f.write("  MULT=1\n")
        f.write("  NPRINT=-5\n")
        f.write("  MAXIT=100\n")
        f.write(" $END\n")

        f.write(" $STATPT\n")
        f.write("  NSTEP=200\n")
        f.write("  OPTTOL=0.00001\n")
        if(atom1!=None and atom2!=None): f.write(f"  IFREEZ(1)={3*atom1-2},{3*atom1-1},{3*atom1},{3*atom2-2},{3*atom2-1},{3*atom2}\n")
        f.write(" $END\n")

        f.write(" $DFT\n")
        # f.write("  JANS=2\n")
        f.write("  NRAD=99\n")
        f.write("  NLEB=590\n")
        f.write(" $END\n")

        f.write(" $SCF\n")
        f.write("  CONV=1.0D-6\n")
        f.write("  MAXVT=50\n")
        f.write("  DAMP=.TRUE.\n") #Helps convergence?
        f.write(" $END\n")

        f.write(" $SYSTEM\n")
        f.write("  MWORDS=50\n")
        f.write(" $END\n")

        #6-311++G(d,p) basis set
        f.write(" $BASIS\n")
        f.write("  GBASIS=N311\n")
        f.write("  NGAUSS=6\n")
        f.write("  NDFUNC=1\n")
        f.write("  NPFUNC=1\n")
        f.write("  DIFFSP=.TRUE.\n")
        f.write("  DIFFS=.TRUE.\n")
        f.write(" $END\n")
        f.write(" $GUESS\n")
        f.write("  GUESS=HUCKEL\n")
        f.write(" $END\n")

        f.write(" $DATA\n")
        f.write("Comment card\n")
        f.write("C1\n")
        for i in range(conf.shape[1]):
            f.write(f"{S[i]:2s} {S_Z_dict[S[i]]:4.1f}  {conf[0,i]:14.10f} {conf[1,i]:14.10f} {conf[2,i]:14.10f}\n")
        f.write(" $END\n")
    return    



def main():
    S = ["H","C"]
    conf = np.zeros([3,2])
    conf[:,0] = [0.0,0.0,0.0]
    conf[:,1] = [1.0,1.0,1.0]
    energy_run(S,conf,"test.inp")

    with open("test.xyz","r") as f:
        Natoms = int(f.readline().strip())
        f.readline()
        conf = np.zeros([3,Natoms])
        S = []

        for i in range(Natoms):
            line = f.readline().strip().split()
            S.append(line[0])
            conf[:,i] = np.array(line[1:])
    energy_run(S,conf,"test.inp")




if(__name__=="__main__"):
    main()
